In [1]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
import numpy as np

Task 1

In [4]:
a = np.matrix("0.05,0.07,0;0.05,0,0.06;1,1,1")
b = np.matrix("2250;1400;50000")
a_solve = np.linalg.solve(a,b)
a_solve

matrix([[10000.],
        [25000.],
        [15000.]])

Task 2

In [5]:
a = np.matrix("0,2,1;2,1,0;1,1,1")
b = np.matrix("1448;1428;1328")
a_solve = np.linalg.solve(a,b)
result = a_solve.astype('int')
result

matrix([[436],
        [556],
        [336]])

Task 3

In [6]:
a = np.matrix("3,0,3;6,0.25,0;1,0.33,1")
b = np.matrix("1;1;1")
a_solve = np.linalg.solve(a,b)
a_solve

matrix([[0.08249158],
        [2.02020202],
        [0.25084175]])

In [7]:
a = round(a_solve[0, 0], 1)
b = round(a_solve[1, 0], 1)
c = round(a_solve[2, 0], 1)
a, b ,c

(0.1, 2.0, 0.3)

In [9]:
def res(n):
    result = 1 / n
    result = round(result, 1)
    return result

In [10]:
a = res(a)
b = res(b)
c = res(c)
a, b, c

(10.0, 0.5, 3.3)

Task 4

In [11]:
a = np.matrix("1,1,1;9,3,1;1,-1,1")
b = np.matrix("12;54;2")
a_solve = np.linalg.solve(a,b)
result = a_solve.astype('int')
result

matrix([[4],
        [5],
        [3]])

Task 5

In [13]:
from numpy import array
def get_polynom(coords: list) -> array:
    a = []
    b = []
    for x, y in coords:
        row = []
        b.append(y)
        for i in range(len(coords)):
            row.append(x ** i)
        a.append(row)
    return np.linalg.solve(a, b).astype('int')

print(get_polynom([(1, 2), (30, 50), (-1, 9)]))

[ 5 -3  0]
